pipeline {
    agent any
    tools{
        maven 'maven_3_5_0'
    }
    stages{
        stage('Build Maven'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/https://github.com/singyabhalse/TheNaturalsBytes/tree/JenkensDemo']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/singyabhalse/TheNaturalsBytes.git']]])
                sh 'mvn clean install'
            }
        }
 
    }
}
