pipeline {
    agent any
    tools{
        maven 'maven_3_5_0'
    }
    stages{
        stage('Build Maven'){
            steps{
              checkout scmGit(branches: [[name: '*/JenkensDemo']], url: 'https://github.com/singyabhalse/TheNaturalsBytes.git']])
                sh 'mvn clean install'
            }
        }
 
    }
}
